BEGIN;

INSERT INTO organizations (id, name, email)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  'HelpBridge Test Org',
  'partners@example.test'
);

INSERT INTO organization_members (organization_id, user_id, role)
VALUES
  ('11111111-1111-1111-1111-111111111111', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'owner'),
  ('11111111-1111-1111-1111-111111111111', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'viewer');

INSERT INTO services (
  id,
  name,
  name_fr,
  description,
  description_fr,
  address,
  address_fr,
  phone,
  url,
  email,
  hours,
  fees,
  eligibility,
  application_process,
  languages,
  bus_routes,
  accessibility,
  last_verified,
  verification_status,
  category,
  tags,
  scope,
  virtual_delivery,
  primary_phone_label,
  created_at,
  authority_tier,
  resource_indicators,
  synthetic_queries,
  synthetic_queries_fr,
  coordinates,
  embedding,
  org_id,
  published,
  provenance
)
VALUES
  (
    'db-food-complete',
    'Food Support Hub',
    'Centre de soutien alimentaire',
    'Food bank and meal support for Kingston residents.',
    'Banque alimentaire et soutien repas pour les residents de Kingston.',
    '123 Princess St, Kingston, ON',
    '123 rue Princess, Kingston, ON',
    '613-555-0101',
    'https://example.test/food',
    'food@example.test',
    '{"monday":{"open":"09:00","close":"17:00"}}'::jsonb,
    'Free',
    'Open to residents',
    'Walk in',
    ARRAY['English', 'French'],
    ARRAY['1', '2'],
    '{"wheelchair":true}'::jsonb,
    '2026-03-01T12:00:00Z',
    'L2',
    'Food',
    '[{"tag":"families","evidence_url":"https://example.test/evidence/families"}]'::jsonb,
    'kingston',
    FALSE,
    'Main line',
    '2026-03-01T12:00:00Z',
    'government',
    '{"staff_size":"large"}'::jsonb,
    ARRAY['food bank', 'meal support'],
    ARRAY['banque alimentaire'],
    '{"lat":44.2312,"lng":-76.4860}'::jsonb,
    '[0.1,0.2,0.3]'::jsonb,
    '11111111-1111-1111-1111-111111111111',
    TRUE,
    '{"verified_by":"Test Verifier","verified_at":"2026-03-01T12:00:00Z","evidence_url":"https://example.test/evidence/food","method":"phone"}'::jsonb
  ),
  (
    'db-fr-housing',
    'Housing Access Centre',
    'Centre d''acces au logement',
    'Housing support and intake for people needing shelter support.',
    'Soutien au logement et aide pour les personnes cherchant un refuge.',
    '456 Bagot St, Kingston, ON',
    '456 rue Bagot, Kingston, ON',
    '613-555-0102',
    'https://example.test/housing',
    'housing@example.test',
    '{"tuesday":{"open":"10:00","close":"18:00"}}'::jsonb,
    NULL,
    'Adults and youth',
    'Call first',
    ARRAY['French'],
    ARRAY['4'],
    '{"wheelchair":false,"elevator":true}'::jsonb,
    '2026-03-05T12:00:00Z',
    'L3',
    'Housing',
    '[{"tag":"newcomers","evidence_url":"https://example.test/evidence/newcomers"}]'::jsonb,
    'kingston',
    FALSE,
    'Intake line',
    '2026-03-05T12:00:00Z',
    'healthcare',
    '{"staff_size":"medium"}'::jsonb,
    ARRAY['housing help', 'shelter support'],
    ARRAY['aide logement', 'refuge'],
    '{"lat":44.2340,"lng":-76.5000}'::jsonb,
    '[0.4,0.5,0.6]'::jsonb,
    '11111111-1111-1111-1111-111111111111',
    TRUE,
    '{"verified_by":"Test Verifier","verified_at":"2026-03-05T12:00:00Z","evidence_url":"https://example.test/evidence/housing","method":"email"}'::jsonb
  ),
  (
    'crisis-988',
    '9-8-8 Suicide Crisis Helpline',
    'Ligne d''aide 9-8-8',
    '24/7 crisis support across Canada.',
    'Soutien de crise 24 h sur 24 partout au Canada.',
    NULL,
    NULL,
    '988',
    'https://example.test/988',
    NULL,
    NULL,
    NULL,
    'Anyone in crisis',
    'Call or text',
    ARRAY['English', 'French'],
    NULL,
    '{"wheelchair":false}'::jsonb,
    '2026-03-10T12:00:00Z',
    'L3',
    'Crisis',
    '[]'::jsonb,
    'kingston',
    TRUE,
    'Crisis line',
    '2026-03-10T12:00:00Z',
    'government',
    '{"service_area_size":"national"}'::jsonb,
    NULL,
    NULL,
    '{"lat":45.4215,"lng":-75.6972}'::jsonb,
    NULL,
    NULL,
    TRUE,
    '{"verified_by":"Test Verifier","verified_at":"2026-03-10T12:00:00Z","evidence_url":"https://example.test/evidence/988","method":"provider"}'::jsonb
  ),
  (
    'db-hidden-unpublished',
    'Hidden Unpublished Service',
    NULL,
    'Should never be returned publicly.',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://example.test/hidden-unpublished',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-03-02T12:00:00Z',
    'L2',
    'Food',
    '[]'::jsonb,
    'kingston',
    FALSE,
    NULL,
    '2026-03-02T12:00:00Z',
    'community',
    NULL,
    ARRAY['hidden'],
    NULL,
    '{"lat":44.2300,"lng":-76.4900}'::jsonb,
    '[1.0,1.1,1.2]'::jsonb,
    NULL,
    FALSE,
    '{"verified_by":"Hidden","verified_at":"2026-03-02T12:00:00Z","evidence_url":"","method":"test"}'::jsonb
  ),
  (
    'db-hidden-deleted',
    'Hidden Deleted Service',
    NULL,
    'Should be filtered because it is soft deleted.',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://example.test/hidden-deleted',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-03-03T12:00:00Z',
    'L2',
    'Food',
    '[]'::jsonb,
    'kingston',
    FALSE,
    NULL,
    '2026-03-03T12:00:00Z',
    'community',
    NULL,
    ARRAY['hidden'],
    NULL,
    '{"lat":44.2300,"lng":-76.4900}'::jsonb,
    '[1.3,1.4,1.5]'::jsonb,
    NULL,
    TRUE,
    '{"verified_by":"Hidden","verified_at":"2026-03-03T12:00:00Z","evidence_url":"","method":"test"}'::jsonb
  ),
  (
    'db-hidden-draft',
    'Hidden Draft Service',
    NULL,
    'Should be filtered because it is draft.',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://example.test/hidden-draft',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '2026-03-04T12:00:00Z',
    'draft',
    'Housing',
    '[]'::jsonb,
    'kingston',
    FALSE,
    NULL,
    '2026-03-04T12:00:00Z',
    'community',
    NULL,
    ARRAY['hidden'],
    NULL,
    '{"lat":44.2300,"lng":-76.4900}'::jsonb,
    '[1.6,1.7,1.8]'::jsonb,
    NULL,
    TRUE,
    '{"verified_by":"Hidden","verified_at":"2026-03-04T12:00:00Z","evidence_url":"","method":"test"}'::jsonb
  );

UPDATE services
SET deleted_at = '2026-03-15T12:00:00Z'
WHERE id = 'db-hidden-deleted';

COMMIT;
